import { createFileRoute } from "@tanstack/react-router";

// @ts-expect-error - route id is auto-generated by TanStack Router plugin
export const Route = createFileRoute("/")({
  component: HomePage,
});

function HomePage() {
  return (
    <div>
      <h1>GymAI - Fitos</h1>
      <p>TanStack Start running</p>
    </div>
  );
}
